# Generated by Django 4.2.7 on 2023-12-02 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id_job', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=55)),
                ('company', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('job_salaire', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('formationreq', models.CharField(max_length=100)),
                ('expreq', models.IntegerField()),
                ('skillreq', models.CharField(max_length=255)),
                ('recruter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id_candidature', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('reqexp', models.CharField(max_length=50)),
                ('reqfor', models.CharField(max_length=50)),
                ('reqskill', models.IntegerField()),
                ('status', models.CharField(default='Waiting', max_length=100)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruter.job')),
            ],
        ),
    ]
