# Generated by Django 4.2.7 on 2023-12-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruter', '0003_company_delete_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pays',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
