# Generated by Django 4.2.7 on 2023-12-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0002_alter_information_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='startyear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='endyear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='startyear',
            field=models.DateField(blank=True, null=True),
        ),
    ]
